- id: "House Occupancy"
  alias: Occupancy
  description: ""
  trigger:
    - entity_id:
        - person.demo
      platform: state
      to: not_home
    - entity_id:
        - person.demo
      platform: state
      to: home
  condition:
    - condition: state
      entity_id: person.demo
      state: not_home
  action:
    - event: house_occupancy
      event_data:
        state: >
        {% if trigger.to_state.state == "home" %}
          "unoccupied"
        {% ifelse trigger.to_state.state == "not_home" %}
          "occupied"
        {% endif %}

