- platform: generic_thermostat
  name: living_room
  heater: input_boolean.heater_living_room
  target_sensor: input_number.living_room_temperature
  min_temp: 15
  max_temp: 30
  ac_mode: false
  target_temp: 20
  cold_tolerance: 2
  hot_tolerance: 1
  initial_hvac_mode: "heat"
- platform: generic_thermostat
  name: bedroom
  heater: input_boolean.heater_bedroom
  target_sensor: input_number.bedroom_temperature
  min_temp: 15
  max_temp: 30
  ac_mode: false
  target_temp: 20
  cold_tolerance: 2
  hot_tolerance: 1
  initial_hvac_mode: "heat"
- platform: generic_thermostat
  name: kitchen
  heater: input_boolean.heater_kitchen
  target_sensor: input_number.kitchen_temperature
  min_temp: 15
  max_temp: 30
  ac_mode: false
  target_temp: 20
  cold_tolerance: 2
  hot_tolerance: 1
  initial_hvac_mode: "heat"
- platform: generic_thermostat
  name: water
  heater: input_boolean.heater_water
  target_sensor: input_number.water_temperature
  min_temp: 60
  max_temp: 65
  ac_mode: false
  target_temp: 60
  cold_tolerance: 2
  hot_tolerance: 1
  initial_hvac_mode: "heat"
