input_boolean.dryer:
  power: 1000
  tick: 0
input_boolean.washing_machine:
  power: 750
  tick: 0
input_boolean.heater_living_room:
  power: 500
  priority: 30
  loss: 0.5
  gain: 2
  tick: 0
input_boolean.heater_bedroom:
  power: 500
  priority: 20
  loss: 0.5
  gain: 2
  tick: 0
input_boolean.heater_kitchen:
  power: 750
  priority: 10
  loss: 0.5
  gain: 2
  tick: 0
input_boolean.heater_water:
  power: 1000
  priority: 50
  loss: 0.5
  gain: 1
  tick: 0
