heater_living_room_ideal:
  min: 16
  max: 30
  initial: 22
  step: 0.5
  mode: slider
  unit_of_measurement: "°C"
heater_bedroom_ideal:
  min: 16
  max: 30
  initial: 22
  step: 0.5
  mode: slider
  unit_of_measurement: "°C"
heater_kitchen_ideal:
  min: 16
  max: 30
  initial: 22
  step: 0.5
  mode: slider
  unit_of_measurement: "°C"
heater_water_ideal:
  min: 60
  max: 65
  initial: 60
  step: 0.5
  mode: slider
  unit_of_measurement: "°C"

# Solar
solar_generation:
  min: 0
  max: 5000
  initial: 0
  mode: slider
  unit_of_measurement: "W"

# Simulation

living_room_temperature:
  min: 0
  max: 40
  unit_of_measurement: "°C"
bedroom_temperature:
  min: 0
  max: 40
  unit_of_measurement: "°C"
kitchen_temperature:
  min: 0
  max: 40
  unit_of_measurement: "°C"
heater_water_temperature:
  min: 0
  max: 40
  unit_of_measurement: "°C"

tick:
  initial: 0
  min: 0
  max: 72
  unit_of_measurement: "Hours"
